# Generated by Django 5.0.6 on 2024-06-19 19:01

import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="Title"),
                ),
                ("bio", djrichtextfield.models.RichTextField(verbose_name="BIO")),
            ],
            options={
                "verbose_name": "Main page",
            },
        ),
    ]
